# Copyright 2021 Concurrent Technologies Corporation, Nteligen LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: Deploy Nightly
on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  nightly:
    name: Deploy nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn install

      - name: Check formatting
        run: |
          yarn run prettier src -c

      - name: Yarn Compile
        run: yarn compile

      - name: Get filename
        run: |
          GIT_ID=$(git describe)
          VSIX_FILE="daffodil-debugger-${GIT_ID}.vsix"
          echo "VSIX_FILE=${VSIX_FILE}" >> $GITHUB_ENV
      
      - name: Create vsix
        run: |
          yarn run package -o ${{env.VSIX_FILE}}
      
      - name: Deploy release
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by github actions
        with:
          upload_url: https://uploads.github.com/repos/jw3/example-daffodil-vscode/releases/45167120/assets{?name,label}
          release_id: 45167120 
          asset_path: ${{github.workspace}}/${{env.VSIX_FILE}}
          asset_name: ${{env.VSIX_FILE}}
          asset_content_type: vsix
          max_releases: 5
